# * Headless service for stable DNS entries of StatefulSet members
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None
