apiVersion: wp.gluo.be/v1alpha1
kind: Wordpress
metadata:
  name: staging-sample
spec:
  state: "Active" #State determines weither or not the current operator should run resources -- If archived, every resources is created but replicas will be set to 0
  size: "Small" #Size specifies the resources for each deployment -- Small, Medium, Large
  tier: "Bronze" #This helps specify the replicas -- Bronze, Silver, Gold
  #Implement locking mechanisme for wordpressInfo values
  wordpressInfo:
    title: "Stagingphase"
    url: "wordpress-cluster.google.gluo.cloud"